apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: happy-farms-welcome-app
  namespace: kube-controller
spec:
  destination:
    namespace: happy-farms
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles:
        - happy-farms-apps/welcome/values.yaml
    path: generic-helm-chart
    repoURL: git@github.com:kieunguyenql/kube-cicd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true